### ISSUE TITLE
Fix coinmarketCap API fetch inside song page. 

### ISSUE THREAD

**Issue by Nlopierre** [nyu-software-engineering/music-through-blockchain#169]
This will be used to get the updated conversion rate from ETH to USD

There is currently an error when making the API fetch. Please correct this

**Comment by tmlee** [comment]
May i recommend also checking out our API for your project. It is public, free, and no keys required.

You probably only need to use https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd but you can do more according to our docs at https://www.coingecko.com/en/api should you need to
