### ISSUE TITLE
Style songInfo modal or ditch it

### ISSUE THREAD

**Issue by isaacblinder** [nyu-software-engineering/music-through-blockchain#184]
The styling for the songInfo modal is incomplete. We need to either fix it or ditch it and just have the song page.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/25308324/56948682-dfc55600-6afe-11e9-826f-86d36d4830f5.png">

<img width="570" alt="image" src="https://user-images.githubusercontent.com/25308324/56948692-e81d9100-6afe-11e9-991f-57de2754c312.png">

**Comment by ann0605** [comment]
Fixed for demo 3
