### ISSUE TITLE
Read documentation to make react compatible with Ethereum

### ISSUE THREAD

**Issue by Nlopierre** [nyu-software-engineering/music-through-blockchain#24]

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-music-through-blockchain - don't forget to assign member(s) of your team to work on each issue in your task board.  Otherwise, nice work with these issues.

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-music-through-blockchain - Is @Nlopierre the only one who needs to know how to use React and Ethereum in your team?  this is a spike that each team member must do independently. For example, if Nico does this into the Done column of the Sprint 0 Task Board, that would show that the entire team has learned this, which would not be accurate. So having only 1 issue for separate pieces of work that are independently need to be done by team members is misleading on the Task Board. Please separate this into different issues, each assigned to one team member. Do the same for the other spikes on your task board that need to be done independently by each team member.  I see very little about any of you having to learn anything during this sprint, which means that your task board is including almost none of the actual work you have to do to move forward.
