### ISSUE TITLE
Plan and design auction or broker system to sell royalties

### ISSUE THREAD

**Issue by Nlopierre** [nyu-software-engineering/music-through-blockchain#61]
Essentially, we want to decide how we want the users to buy royalties and what options can the artists have to sell them. Do we want a simple auction system? Or do we want a craiglist kind of deal (post the price, buy it if you want)? I think the auction makes more sense but we would also need a UI for it, and I don't know if this would be more complicated than simply creating a post. What do you think?

**Comment by ann0605** [comment]
I think it would be more complicated to have the auction system, but it would be really cool to have that.
